### ISSUE TITLE
How to define custom formatter?

### ISSUE THREAD

**Issue by louis77** [undtec/ChartJS#1]
In Chart.js one can define a custom formatter in the datalabels plugin:

<img width="506" alt="CleanShot 2022-07-11 at 11 00 04@2x" src="https://user-images.githubusercontent.com/1240462/178227851-3aab5ba5-4965-4c8a-944f-2eeae79d1d2c.png">

How could we make this possible in Xojo ?

**Comment by undtec** [comment]
As far as I know the datalabels plugin is not part of the basic Chart.js

Maybe someone can add the plugin to this WebSDK.
